version: '3.7'

services:
  api-app:
    build:
      context: .
      dockerfile: config/docker/dev/app/Dockerfile
    networks:
      - mycompany_network_backend
    labels:
      traefik.enable: true
      traefik.http.routers.api-app.rule: "Host(`app.example.dev`)"
      traefik.http.routers.api-app.tls: true
      traefik.http.services.api-app.loadbalancer.server.port: 8080

  app-redis:
    image: redis:alpine
    networks:
      - mycompany_network_backend

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "event-sourcing-lab-cookie"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI
    networks:
      - mycompany_network_backend

networks:
  mycompany_network_backend:
    external: true
